urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings
from expwatch.urls import urlpatterns as exps_patterns
from groupsite.urls import urlpatterns as gmao_patterns

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^exps/', include(exps_patterns)),
    url(r'', include(gmao_patterns)),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

groupsite/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from cmipstatus.models import People
from django.contrib.syndication.views import Feed
from django.core.mail import send_mail
from django.db.models.signals import post_save
from django.dispatch import receiver


class News(models.Model):
    title = models.CharField(max_length=200, verbose_name="Título")
    content = models.CharField(max_length=4096, verbose_name="Descrição")
    long_content = models.TextField(default=" ", verbose_name="Conteúdo")
    when = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(People)
    approved = models.BooleanField(default=False)
    besm = models.BooleanField(default=False)

    def get_absolute_url(self):
        return "http://antares.ccst.inpe.br/gmao/news/{0}".format(self.id)

    def __unicode__(self):
        return self.title


class NewsImg(models.Model):
    news = models.ForeignKey('News', verbose_name="Notícia")
    img = models.ImageField(max_length=1024, upload_to='media', verbose_name="Imagem")
    description = models.TextField(default='')

    def __unicode__(self):
        return self.news.title


class NewsAttachment(models.Model):
    news = models.ForeignKey('News', verbose_name="Notícia")
    attachment = models.FileField(max_length=1024, upload_to='attachments', verbose_name="Arquivo")
    description = models.TextField(default='')

    def __unicode__(self):
        return self.attachment.__unicode__()


class ScienceThing(models.Model):
    short = models.CharField(max_length=256, verbose_name="Título")
    description = models.CharField(max_length=2048, verbose_name="Descrição")
    approved = models.BooleanField(default=False)
    besm = models.BooleanField(default=False)

    def __unicode__(self):
        return self.short


class YoutubeVideo(models.Model):
    science_thing = models.ForeignKey('ScienceThing')
    video_link = models.CharField(max_length=1024, verbose_name="Link do Vídeo (embed)")

    def __unicode__(self):
        return self.science_thing.short


class Graphic(models.Model):
    science_thing = models.ForeignKey('ScienceThing')
    data_file = models.FileField(max_length=102, upload_to='graphics_descriptions', verbose_name="Arquivo de Definição")

    def __unicode__(self):
        return self.science_thing.short

    def get_graphic_data(self):
        TYPE_LINE = 0
        AXIS_NAMES_LINE = 1
        LABELS_LINE = 2
        DATA_START_LINE = 3
        f = open(self.data_file.path, 'r')
        text = f.readlines()
        f.close()
        graphic_type = text[TYPE_LINE][:-1]
        graphic_axis_names = text[AXIS_NAMES_LINE][:-1].split(',')
        graphic_labels = text[LABELS_LINE][:-1].split(',')
        graphic_data = [t[:-1] for t in text[DATA_START_LINE:]]
        return [{'type': graphic_type, 'axis':graphic_axis_names, 
            'labels':graphic_labels, 'data':graphic_data}]


class Post(models.Model):
    title = models.CharField(max_length=512, verbose_name="Título")
    description = models.TextField(default=" ", verbose_name="Descrição")
    content = models.TextField(default=" ", verbose_name="Conteúdo")
    using_markdown = models.BooleanField(default=False, verbose_name="Usando Markdown?")
    when = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(People)
    approved = models.BooleanField(default=False)
    besm = models.BooleanField(default=False)

    def get_absolute_url(self):
        return "http://antares.ccst.inpe.br/gmao/posts/{0}".format(self.id)


    def __unicode__(self):
        return self.title


class PostImg(models.Model):
    post = models.ForeignKey('Post', verbose_name="Post")
    img = models.ImageField(max_length=1024, upload_to='media', verbose_name="Imagem")
    description = models.TextField(default='')

    def __unicode__(self):
        return self.post.title


class PostAttachment(models.Model):
    post = models.ForeignKey('Post', verbose_name="Post")
    attachment = models.FileField(max_length=1024, upload_to='attachments', verbose_name="Arquivo")
    description = models.TextField(default='')

    def __unicode__(self):
        return self.attachment.__unicode__()
    

class Publication(models.Model):
    title = models.CharField(max_length=256, verbose_name="Título")
    description = models.TextField(default="", verbose_name="Descrição")
    when = models.DateTimeField(auto_now_add=True)
    publication_date = models.DateField(verbose_name="Data de Publicação")
    author = models.ForeignKey(People)
    pdf = models.FileField(max_length=1024, upload_to='publications', verbose_name="Arquivo")
    besm = models.BooleanField(default=False)

    def __unicode__(self):
        return ', '.join([self.title, self.author.name])



class NetworkInfo(models.Model):
    TWITTER_ICON = '/media/twitter-bird-white-on-blue.png'
    LINKEDIN_ICON = '/media/LinkedIn_IN_Icon_25px.png'
    GOOGLE_PLUS_ICON = '/media/googleplus-logo.png'
    FACEBOOK_ICON = '/media/f_logo.png'
    WEBSITE_ICON = '/media/Web-Site-icon.png'
    LATTES_ICON = '/media/icon_lattes.png'
    GITHUB_ICON = '/media/github-icon.png'
    BITBUCKET_ICON = '/media/Bitbucket.png'

    people = models.ForeignKey(People)
    lattes = models.CharField(max_length=256, blank=True)
    twitter = models.CharField(max_length=256, blank=True)
    linkedin = models.CharField(max_length=256, blank=True)
    google_plus = models.CharField(max_length=256, blank=True)
    github = models.CharField(max_length=256, blank=True)
    bitbucket = models.CharField(max_length=256, blank=True)
    facebook = models.CharField(max_length=256, blank=True)
    site = models.CharField(max_length=256, blank=True)

    def __unicode__(self):
        return self.people.name


    def social_icons(self):
        social = []
        if self.lattes:
            social.append({'link':self.lattes, 'icon':self.LATTES_ICON})
        if self.linkedin:
            social.append({'link':self.linkedin, 'icon':self.LINKEDIN_ICON})
        if self.bitbucket:
            social.append({'link':self.bitbucket, 'icon':self.BITBUCKET_ICON})
        if self.github:
            social.append({'link':self.github, 'icon':self.GITHUB_ICON})
        if self.twitter:
            social.append({'link':self.twitter, 'icon':self.TWITTER_ICON})
        if self.google_plus:
            social.append({'link':self.google_plus, 'icon':self.GOOGLE_PLUS_ICON})
        if self.facebook:
            social.append({'link':self.facebook, 'icon':self.FACEBOOK_ICON})
        if self.site:
            social.append({'link':self.site, 'icon':self.WEBSITE_ICON})
        return social


class LattesCache(models.Model):
    text = models.TextField(default='')
    people = models.ForeignKey(People)
    last_update = models.DateField(auto_now_add=True, auto_now=True)

    def __unicode__(self):
        return "cache " + self.people.name


class Editor(models.Model):
    people = models.ForeignKey(People)
    email = models.EmailField()

    def __unicode__(self):
        return "Editor " + self.people.name


class AmbarPeople(models.Model):
    people = models.ForeignKey(People)
    email = models.EmailField()

    def __unicode__(self):
        return "Ambar " + self.people.name


class PostsFeed(Feed):
    title = "GMAO Blog Feed"
    link = "http://antares.ccst.inpe.br/gmao/blog/"
    description = "Latest posts from GMAO team"
    description_template = "gmaofeedpost.html"

    def items(self):
        return Post.objects.order_by('-when')[:10]

    def item_title(self, item):
        return item.title


class NewsFeed(Feed):
    title = "GMAO News Feed"
    link = "http://antares.ccst.inpe.br/gmao/news/"
    description = "Latest news from GMAO"
    description_template = "gmaofeednews.html"

    def items(self):
        return News.objects.order_by('-when')[:10]

    def item_title(self, item):
        return item.title

REPORT_SEND_HEADER = '[Relatorios] {} enviou relatorio'
REPORT_SEND_BODY = '{},\n{} enviou um relatorio. Para aprova-lo, {}'
REPORT_APPR_HEADER = '[Relatorios] Seu relatorio foi aprovado'
REPORT_APPR_BODY = '{},\nSeu relatorio enviado em {} foi aprovado.'
REPORT_DENY_HEADER = '[Relatorios] Seu relatorio foi rejeitado'
REPORT_DENY_BODY = '{},\nSeu relatorio enviado em {} foi rejeitado.'
REPORT_FORW_HEADER = '[Relatorios] Relatorio enviado por {}'
REPORT_FORW_BODY = 'Relatorio enviado por {}, anexo.'



class AmbarReport(models.Model):
    when = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(People)
    approved = models.BooleanField(default=False)
    attachment = models.FileField(max_length=1024, upload_to='attachments', verbose_name="Arquivo")

    def __unicode__(self):
        return ', '.join([self.author.name, str(self.when)])


    def approve(self):
        self.approved = True
        #notify author
        recipient = AmbarPeople.objects.get(people=self.author).email
        send_mail(
            REPORT_APPR_HEADER,
            REPORT_APPR_BODY.format(self.author.name, self.when),
            'ocean',
            [recipient]) 

        from configs import ambar_email
        send_mail(
            REPORT_FORW_HEADER,
            REPORT_FORW_BODY.format(self.author.name),
            'ocean',
            [ambar_email]) 
        


    def deny(self):
        #notify author
        recipient = AmbarPeople.objects.get(people=self.author).email
        send_mail(
            REPORT_DENY_HEADER,
            REPORT_DENY_BODY.format(self.author.name, self.when),
            'ocean',
            [recipient]) 


@receiver(post_save, sender=AmbarReport)
def notify_submit_report(sender, instance, created, **kwargs):
    if not created:
        return
    report = instance
    approvers = Editor.objects.all()
    for approver in approvers:
        send_mail(
            REPORT_SEND_HEADER.format(report.author.name),
            REPORT_SEND_BODY.format(approver.people.name, report.author.name, 'link'),
            'ocean',
            [approver.email]) 

templates/cmipnews.html
{% extends 'cmiphome.html' %}

{% block body %}
<div class="container">
    <div class="row"><br>
        <div class="span10">

            <div class="well">
                <h2>Events</h2>
                <h3>You can subscribe to the <a class="rss_link" href="/cmip/news/feed/"><img src="/media/feed-icon-28x28.png"/>RSS Feed</a></h3>
            </div>

            <div class="well">
                <ul class="unstyled">
                    {% for log in logs %}
                        <li>{{ log.message }}<span class="small-info">{{ log.when }}</span></li>
                    {% empty %}
                        <li>No logs</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
</div>
{% endblock %}

templates/expsalertview.html
{% extends 'expshome.html' %}

{% block body %}
<div class="container">
    <div class="row"><br>
        <div class="span10">
            <div class="well">
                <h2>Alert</h2>
                <p><strong>Experiment</strong>
                    <a href="/exps/expview/{{ alert.exp.id }}">{{ alert.exp.name }}</a>
                </p>
                <p><strong>Message</strong> {{ alert.message }}</p>
                <p><strong>Created at</strong> {{ alert.when }}</p>
                <p><a class="btn" href="/exps/alert/dismiss/{{ alert.id }}">Dismiss</a></p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/expshome.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/media/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/media/css/gmao_style.css" />
        {% block cabecalho %}
             <title>Experiments Status</title>
        {% endblock %}
    </head>

    <body>
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <ul class="nav">
                            <li class="active"><a class="brand" href="/exps/">EXPStatus</a></li>
                            <li><a href="/exps/list/">Experiments</a></li>
                            <!--<li><a href="/exps/news/">News</a></li>
                            <li><a href="/exps/outputs/">Outputs</a></li>-->
                            <li><a href="/exps/filecheck/">FileCheck</a></li>
                            <li><a href="/">GMAO</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="/exps/logout/">Logout</a></li>
                            {% else %}
                                <li><a href="/exps/login/">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>

        <div id="wrap">
            <div id="main" class="container clear-top">
                <div class="banner">
                    <div class="container">
                        <div class="row"><br>
                            <div class="span12">
                                {% block pagebanner %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>

                {% block body %}
                    <div class="hero-unit">
                        <h2>Welcome to BESM Experiments monitoring!</h2>
                    </div>
                {% endblock %}
            </div>
        </div>

        <div class="footer">
            <div class="container">
                <div class="row"><br>
                    <div class="span12">
                        Grupo de Modelagem Oceano-Atmosfera - INPE - Brasil
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="/media/js/jquery-1.7.2.min.js"></script>
        <script type="text/javascript" src="/media/js/jquery-ui-1.8.2.custom.min.js"></script>

        <script type="text/javascript" src="/media/js/bootstrap.js"></script>
        <script type="text/javascript" src="/media/js/bootstrap-collapse.js"></script>
        {% block scripts %}
        {% endblock %}
    </body>
</html>

templates/expsview.html
{% extends 'expshome.html' %}

{% block body %}
<div class="container">
    <div class="row"><br>
        <div class="span10">
            <div class="well">
                <h2>Experiment: {{ exp.name }}</h2>
                <p>Click exp/member name to see its figures</p>
            </div>
        </div>
    </div>
</div>

{{ minfo }}

<div class="container">
    <div class="row"><br> <!-- start exps row -->
        <div class="span10"> <!-- span exps -->
            <div class="well"> <!-- well exps -->
                {% for member_info in info.run_info %}
                    <div class="row"><br><!-- row interno -->
                        <div class="span2"><!-- span sinal+nome -->
                            {% if member_info.post %}
                <img src="/media/azul.png" width=10 title="Post-Processing"/>
                            {% elif  member_info.running %}
                <img src="/media/verde.png" width=10 title="Running"/>
                            {% elif member_info.aborted %}
                <img src="/media/vermelho.png" width=10 title="Error"/>
                            {% elif member_info.complete %}
                <img src="/media/final.png" width=10 title="Finished"/>
                            {% elif member_info.error %}
                <img src="/media/vermelho.png" width=10 title="Error"/>
                            {% else %}
                <img src="/media/amarelo.png" width=10 title="Waiting/Copying"/>
                            {% endif %}
                <a href="/exps/member/{{ member_info.id }}">{{ member_info.member }}</a>
                        </div><!-- fim span sinal+nome -->
                        <div class="span3"><!-- span progress -->
                            <div class="progress progress-striped active" title="{{ member_info.text_total }}%">
                              <div class="bar" style="width: {{ member_info.text_total }}%"></div>
                            </div>
                        </div><!-- fim span progress -->
                        <div class="span3"><!-- span descricao -->

                            <span 
                title="{% if member_info.running %}[{{ member_info.text_run }}% on run {{ member_info.current }}{% else %}[Completed {{ member_info.last }} runs{% endif %} of {{ member_info.total }}]">

                                {% if not member_info.complete %}
                                    {{ member_info.text_total }}% ({{ member_info.finished_years }} 
                                    years of {{ member_info.total_years }})
                                {% else %}
                                    {% if member_info.aborted %}
                                        Aborted in
                                    {% else %}
                                        Completed 
                                    {% endif %}
                                    {{ member_info.finished_years }} years.
                                    {% if member_info.error %}
                                        Error ocurred in last run.
                                    {% endif %}
                                {% endif %}
                                {% if member_info.total_errors %}
                                    Total errors: {{ member_info.total_errors }}
                                {% endif %}
                            </span>
                        </div><!-- fim span descricao -->
                    </div><!-- fim row interno -->
                {% empty %}
                    <p>No jobs submitted</p>
                {% endfor %}
                <br><p>Total errors in this list: {{ info.page_errors }}</p>
            </div><!-- fim well -->
        </div><!-- fim span exps -->
    </div><!-- fim row exps -->
</div><!-- fim container exps -->

    {% if user %}
        <div class="container">
            <div class="row"><br>
                <div class="span10">
                    <div class="well">
                        <h3>README</h3>
                        <p>{% for line in readme %}
                                <br>{{ line }}
                           {% endfor %}</p>

<!--
                        <h3>Discussion ({{ comments.count }})</h3>
                        {% for comment in comments %}
                            <br>
                            <p class="post-body">{{ comment.text }}</p>
                            <p><span class="small-info">{{ comment.author }}</p></span>
                        {% empty %}
                            <p>No comments in this experiment</p>
                        {% endfor %}
                        <form class="well" method="post" id="form" action="" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button class='btn' type="submit">Submit Comment</button>
                        </form>
-->

                    </div><!-- fim well -->
                </div><!-- fim span -->
            </div><!-- fim row -->
        </div><!-- fim container -->
    {% endif %}

{% endblock %}

templates/gmaoambarreports.html
{% extends 'gmaobase.html' %}

{% block cabecalho %}Aguardando Aprovação{% endblock %}

{% block pagebanner %}
<h2>Aguardando Aprovação</h2>
{% endblock %}

{% block body %}
<div class="news">
    <div class="container">
        <div class="row"><br>
            <div class="span12">
                <h3>Relatórios Pendentes</h3>
                <ul class="news-list">
                    {% for r in reports %}
                        <li class="sci-item">
                            <a href="{{ r.attachment.url }}">Enviado em {{ r.when }}</a>
                        {% if approver %}
                            por <a href="/people/{{ r.author.id }}">{{ r.author.name }}</a>
                            <a href="/restricted/approve_report/{{ r.id }}" 
                               class="btn btn-small"><i class="icon-ok"></i> Aprovar</a>
                            <a href="/restricted/deny_report/{{ r.id }}" 
                               class="btn btn-small"><i class="icon-trash"></i> Apagar</a>
                        {% endif %}
                        </li>
                    {% empty %}
                        <li class="sci-item">Nenhum item</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row"><br>
            <div class="span12">
                <h3>Relatórios Aprovados</h3>
                <ul class="news-list">
                    {% for r in old %}
                        <li class="sci-item">
                        <a href="{{ r.attachment.url }}">Enviado em {{ r.when }}</a>
                        {% if approver %}
                            por <a href="/people/{{ r.author.id }}">{{ r.author.name }}</a>
                        </li>
                        {% endif %}
                    {% empty %}
                        <li class="sci-item">Nenhum item</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/gmaocreatenews.html
{% extends "gmaobase.html" %}

{% block cabecalho %}Escrever Notícia{% endblock %}

{% block pagebanner %}
    <h2>Criar Notícia</h2>
{% endblock %}

{% block body %}
<div class="news-edit">
    {% if erro %}
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <strong>Erro!</strong><br>Entradas inválidas
        </div>
    {% endif %}

    <form class="well" method="post" action="" enctype="multipart/form-data" class="infotabs accfrm news">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit"><i class="icon-ok"></i> Salvar</button>
    </form>
</div>
{% endblock %}

templates/gmaofeednews.html
<p><i>{{ obj.content }}</i></p>

{{ obj.long_content }}

templates/gmaofeedpost.html
{% load markup %}

<p><i>{{ obj.description }}</i></p>

{{ obj.content|markdown }}

templates/gmaopeople.html
{% extends 'gmaobase.html' %}

{% block cabecalho %}Equipe{% endblock %}

{% load thumbnail %}

{% block pagebanner %}
    <h2>Equipe GMAO</h2>
{% endblock %}

{% block body %}
<div class="people">
    <div class="container">
        {% for row in people %}
            <div class="row"><br>
                {% for p in row %}
                    <div class="span4">
                        <div class="well">
                            <a href="/people/{{ p.id }}">
                                <div class="span1">
                                    {% thumbnail p.photo "x30" crop="center" as photo %}
                                        <img src="{{ photo.url }}">
                                    {% endthumbnail %}
                                </div>
                                <div class="span2">
                                    {{ p.name }}
                                </div>
                            </a>
                        </div>                
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/gmaopeopleview.html
{% extends "gmaobase.html" %}

{% load thumbnail %}

{% block cabecalho %}{{ people.name }}{% endblock %}

{% block pagebanner %}
<div class="hero-unit">
    <h2>{{ people.name }}</h2>
</div>
{% endblock %}

{% block body %}
<div class="profile">
<div class="container">
<div class="row"><br>

<div class="span4">
    <div class="thumbnail">
        {% thumbnail people.photo "x300" crop="center" as photo %}
            <img src="{{ photo.url }}">
        {% endthumbnail %}
    </div><br>
    {% if social %}
    <div class="well">
        <h4>Networking</h4>
        {% for nw in social %}
            <a href="{{ nw.link }}"><img height=25 class="social-icon" src="{{ nw.icon }}"></a>
        {% endfor %}
    </div>
    {% endif %}
</div>

<div class="span8">
    <div class="well">
        <h3>Sobre</h3><br>
        <p>{{ people.about|linebreaksbr|urlize }}</p>
    </div>
    <div class="well"> 
        <h3>Posts</h3><br>
        {# posts by this person #}
        <ul class="post-list">
            {% for post in posts %}
                <li class="post-item"><a href="/posts/{{ post.id }}">{{ post.title }}</a></li>
                <li class="post-timestamp">{{ post.when }}</li>
            {% endfor %}
        </ul>
    </div>

    <div class="well">
        <h3>Publicações para Download</h3><br>
        <ul class="post-list">
            {% for pub in publications %}
            <li class="post-item"><a href="{{ pub.pdf.url }}"><img src="/media/pdficon_large.png"> {{ pub.title }}</a> <span class="post-timestamp">{{ pub.publication_date }}</span></li>
            <li>
            <div class="accordion" id="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ pub.id }}">Abstract</a>
                    </div>
                    <div id="collapse{{ pub.id }}" class="accordion-body collapse in">
                        <div class="accordion-inner">
                            <span class="post-description">{{ pub.description|linebreaksbr }}</span>
                        </div>
                    </div>
                </div>
            </div>
            </li>
            {% endfor %}
        </ul>
        <h3>Lattes</h3>
            <div class="accordion" id="accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseLattes">Todas as Publicações</a>
                    </div>
                    <div id="collapseLattes" class="accordion-body collapse in">
                        <div class="accordion-inner">
                            {% for publication in lattes %}
                                <p><strong>{{ publication.authors }}</strong> {{ publication.publication }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            </li>
        </ul>
    </div>
</div>

</div>
</div>
</div>
{% endblock %}

templates/gmaopostview.html
{% extends 'gmaobase.html' %}

{% load thumbnail %}

{% block cabecalho %}
{{ post.title }}
{% endblock %}

{% block pagebanner %}
{% endblock %}

{% block body %}
<div class="post-view">
<div class="container">
    <div class="row"><br>
        <div class="span12">
            <h2>{{ post.title }}</h2>
            <span class="author"><a href="/people/{{ post.author.id }}">{{ post.author }}</a></span>
            <span class="post-timestamp">{{ post.when }}</span><br>
            <span class="post-description">{{ post.description|linebreaksbr }}</span>
        </div>
    </div>

    <div class="row"><br>
        <div class="span12">
            {% if post.using_markdown %}
                {% load markup %}
                <div class="post-body">{{ post.content|markdown }}</div>
            {% else %}
                <p class="post-body">{{ post.content|linebreaksbr|urlize }}</p>
            {% endif %}
            <p>Por: <span class="author"><a href="/people/{{ post.author.id }}">{{ post.author }}</a></span></p>
        </div>
    </div>

        {% if imgs %}
            <div class="row"><br>
                <div class="span12">
                  <div class="well">
                    <h3>Imagens</h3>
                    {% for img in imgs %}
                        <div class="row"><br>
                            <div class="span2">
                                {% thumbnail img.img "x100" crop="center" as im %}
                                    <a href="{{ img.img.url }}"><img src="{{ im.url }}" title="{{ img.description }}"></a>
                                {% endthumbnail %}
                            </div>
                            <div class="span9">
                                {{ img.description }}
                            </div>
                        </div>
                    {% endfor %}
                  </div>
                </div>
            </div>
        {% endif %}
        {% if attach %}
            <div class="row"><br>
                <div class="span12">
                  <div class="well">
                    <h3>Arquivos Anexos</h3>
                    {% for att in attach %}
                        <p><i class="icon-download-alt"></i>
                            <a href="{{ att.attachment.url }}">
                        {% if att.description %}
                            {{ att.description }}
                        {% else %}
                            {{ att }}
                        {% endif %}
                            </a></p>
                    {% endfor %}
                  </div>
                </div>
            </div>
        {% endif %}

</div>
</div>
{% endblock %}

templates/gmaoscience.html
{% extends 'gmaobase.html' %}

{% block cabecalho %}Ciência{% endblock %}

{% block pagebanner %}
<h2>{{ science_type }}</h2>
{% endblock %}

{% block body %}
<div class="news">
<div class="container">
<div class="row"><br>
    <div class="span12">
    <ul class="news-list">
        {% for sci in sciences %}
            <li class="sci-item"><a href="/{{ sci_link }}/{{ sci.id }}">{{ sci.short }}</a></li>
        {% endfor %}
    </ul>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/gmaouploadpublication.html
{% extends "gmaobase.html" %}

{{ form.media }}

{% block cabecalho %}Enviar Publicação{% endblock %}

{% block pagebanner %}
    <h2>Enviar Publicação</h2>
{% endblock %}

{% block body %}
<div class="image-edit">
    {% if erro %}
        <div class="alert alert-error">
            <a class="close" data-dismiss="alert">×</a>
            <strong>Erro!</strong><br>Entradas inválidas
        </div>
    {% endif %}

    <form class="well" method="post" action="" enctype="multipart/form-data" class="infotabs accfrm pub">
        {% csrf_token %}
        {% for field in form %}
            {% if field.name == 'publication_date'%}
                <p>{{ field.label }}<br><input type="date" name="publication_date" id="id_publication_date" /></p>
            {% else %}
                <p>{{ field.label }}<br>{{ field }}</p>
            {% endif %}
        {% endfor %}
        {# form.as_p #}
        <button class="btn" type="submit"><i class="icon-ok"></i> Enviar</button>
    </form>
</div>
{% endblock %}